### ISSUE TITLE
bug 7 - voice access doesn't work on android 11 devices

### ISSUE THREAD

**Issue by ghost** [COSC481W-2024Winter/JARVIS#83]
problem:
E/flutter (26535): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(recognizerNotAvailable, Speech recognition not available on this device, , null)
E/flutter (26535): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
E/flutter (26535): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322)
E/flutter (26535): <asynchronous suspension>
E/flutter (26535): #2      MethodChannelSpeechToText.initialize (package:speech_to_text_platform_interface/method_channel_speech_to_text.dart:39)
E/flutter (26535): <asynchronous suspension>
E/flutter (26535): #3      SpeechToText.initialize (package:speech_to_text/speech_to_text.dart:300)
E/flutter (26535): <asynchronous suspension>
E/flutter (26535): #4      _HomeScreenState._startListening (package:jarvis/home.dart:282)
E/flutter (26535): <asynchronous suspension>

**Comment by ghost** [comment]
we have decided that supporting such an old version is out of scope for a flutter application.
